version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/volume/data/:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/volume/log/:/var/log/rabbitmq/
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=restaurantdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - 27017:27017