version: "3.9"
services:
  menu-service:
    build:
      dockerfile: "../docker/Dockerfile"
      context: "../MenuService"
      target: "test"
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - "8080:8080"
  order-service:
    build:
      dockerfile: "../docker/Dockerfile"
      context: "../OrderService"
      target: "test"
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - "8081:8081"
  table-service:
    build:
      dockerfile: "../docker/Dockerfile"
      context: "../TableService"
      target: "test"
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - "8082:8082"
  user-service:
    build:
      dockerfile: "../docker/Dockerfile"
      context: "../UserService"
      target: "test"
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - "8083:8083"
  storage-service:
    build:
      dockerfile: "../docker/Dockerfile"
      context: "../StorageService"
      target: "test"
    depends_on:
      - rabbitmq
      - mongo
    ports:
      - "8084:8084"
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq/volume/data/:/var/lib/rabbitmq/mnesia
      - ./rabbitmq/volume/log/:/var/log/rabbitmq/
  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=restaurantdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"

networks:
  default:
    driver: bridge