name: Test All Services

on:
  # Trigger the workflow on push or pull request events
  push:
  pull_request:

  # Allow running this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Testing Docker-Compose
        uses: sudo-bot/action-docker-compose@latest
        with:
          cli-args: "-f ./docker/docker-compose.test.yml up"
